const { chromium } = require("playwright");
const http=require("http"),fs=require("fs"),path=require("path");
const R="/home/user/europedoor/site";
const srv=http.createServer((q,s)=>{let u=decodeURIComponent(q.url.split("?")[0]);let f=path.join(R,u);
 if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,"index.html");
 if(!fs.existsSync(f))f=path.join(R,u+"/index.html");
 if(!fs.existsSync(f)){s.writeHead(404);return s.end("x");}
 const e=path.extname(f);
 s.writeHead(200,{"Content-Type":{".json":"application/json",".css":"text/css",".js":"text/javascript"}[e]||"text/html"});s.end(fs.readFileSync(f));});
srv.listen(0,async()=>{const base="http://127.0.0.1:"+srv.address().port;
 const b=await chromium.launch({executablePath:"/opt/pw-browsers/chromium"});
 const p=await b.newPage({viewport:{width:1100,height:900}});
 p.on("pageerror",e=>console.log("PAGEERROR",e.message));
 await p.goto(base+"/plan",{waitUntil:"networkidle"});
 await p.fill("#days","12"); await p.fill("#budget","2500");
 for (const i of ["history","food"]) await p.check(`input[name="interest"][value="${i}"]`);
 await p.click('#planner button[type="submit"]');
 await p.waitForSelector("#result .leg");
 console.log("BEFORE:", (await p.locator("#result .leg h3 a").allTextContents()).join(" > "));
 await p.click('[data-whatif="quieter"]'); await p.waitForTimeout(250);
 console.log((await p.locator("#whatif-out").innerText()).split("\n").filter(Boolean).slice(0,5).join("\n  "));
 await p.click("#whatif-apply"); await p.waitForTimeout(400);
 console.log("AFTER APPLY:", (await p.locator("#result .leg h3 a").allTextContents()).join(" > "));
 console.log("NOTICE:", (await p.locator("#result .note").first().innerText()).split("\n")[0]);
 await b.close();srv.close();});
