#!/usr/bin/env python3
"""The invariant register: what must NOT move while something else does.

    python3 tools/invariants.py --write    measure and record
    python3 tools/invariants.py --check    recompute and compare

A visual migration is a controlled experiment, and an experiment needs a
control. This is it: the things that were true before the change and must
still be true after it. Not "we intend to keep these" — recomputed on every
build, and the build stops when one moves.

The distinction that makes it useful is the KIND of each invariant:

    exact    it must equal this. A second page shell, a sixth application.
    ceiling  it must not exceed this. Font sizes, breakpoints, shadows.
    floor    it must not fall below this. A primitive's reach across pages.

A ceiling is not a target. Thirteen font sizes is not a goal to defend to the
death; it is a line that should only be crossed on purpose, in a diff somebody
reads. Updating this file IS the deliberate act — which is why the register
records a `why` for every row: an invariant you cannot explain is one nobody
can decide to change.

Not everything checkable belongs here. This register holds the things a
VISUAL change could plausibly break while looking like it worked, because
those are the ones that get discovered late and by somebody else.
"""

import glob
import hashlib
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "site")
REG = os.path.join(ROOT, "docs", "invariants.json")


def _css():
    return open(os.path.join(ROOT, "assets", "css", "europedoor.css"),
                encoding="utf-8").read()


def _pages():
    return sorted(glob.glob(os.path.join(OUT, "**", "*.html"), recursive=True))


def _reachable():
    """How many of the declared motifs any destination actually draws."""
    sys.path.insert(0, os.path.join(ROOT, "tools"))
    from lib import data as D                                      # noqa: E402
    from lib import render as R                                    # noqa: E402
    d = D.load()
    seen = set()
    for node in d["cities"].values():
        t, r = node["city"], node["region"]
        seen.add(R.motif_for(t["interests"], t.get("city_type"))
                 or R.motif_for(r["interests"]))
    return len(seen & set(R.MOTIFS))


def measure():
    css = _css()
    pages = _pages()
    bodies = {p: open(p, encoding="utf-8").read() for p in pages}

    routes = sorted("/" + os.path.relpath(p, OUT).replace("index.html", "").rstrip("/")
                    for p in pages)
    route_hash = hashlib.sha256("\n".join(routes).encode()).hexdigest()[:16]

    prim_floor = {}
    for prim in ("kicker", "masthead", "pagehead", "crumbs", "row", "card",
                 "band", "note", "facts", "btn", "chip"):
        hit = sum(1 for b in bodies.values()
                  if re.search(r'class="[^"]*\b' + prim + r'\b', b))
        prim_floor[prim] = round(hit / len(pages), 3)

    apps, enh = [], []
    for js in sorted(glob.glob(os.path.join(ROOT, "assets", "js", "*.js"))):
        body = open(js, encoding="utf-8").read()
        (apps if ("fetch(" in body or "localStorage" in body) else enh).append(
            os.path.basename(js))

    sys.path.insert(0, os.path.join(ROOT, "tools"))
    from lib import render as R                                    # noqa: E402

    return {
        "$comment": "GENERATED by tools/invariants.py --write. The control for "
                    "every visual experiment: what must not move while "
                    "something else does. `kind` is exact / ceiling / floor. "
                    "Changing a value here is the deliberate act — do it in a "
                    "commit that says why.",
        "invariants": {
            "routes.count": {
                "value": len(pages), "kind": "exact",
                "why": "A visual change must not add or remove a page. If this "
                       "moves during a restyle, something is generating pages "
                       "from a stylesheet, which is a different kind of bug."},
            "routes.hash": {
                "value": route_hash, "kind": "exact",
                "why": "A visual change must not move a URL. Every inbound link, "
                       "every social card and every sitemap entry depends on "
                       "this set being stable."},
            "shell.count": {
                "value": sum(open(os.path.join(ROOT, "tools", "lib", f),
                                  encoding="utf-8").read().count("<!doctype html>")
                             for f in ("render.py", "pages.py")),
                "kind": "exact",
                "why": "One function emits <html>. A second is how a masthead "
                       "comes to exist twice and diverges within a month."},
            "shell.mastheads_per_page": {
                "value": max(b.count('class="masthead"') for b in bodies.values()),
                "kind": "exact",
                "why": "Exactly one, on every page."},
            "shell.footers_per_page": {
                "value": max(b.count("<footer") for b in bodies.values()),
                "kind": "exact", "why": "Exactly one, on every page."},
            "css.stylesheets": {
                "value": len(glob.glob(os.path.join(ROOT, "assets", "css", "*.css"))),
                "kind": "exact",
                "why": "One stylesheet. Two is how a design system forks."},
            "css.font_families": {
                "value": len(re.findall(r"--(?:display|text|mono):", css)),
                "kind": "exact",
                "why": "Three: a display serif, a system sans, a mono."},
            "css.webfonts": {
                "value": len(re.findall(r"@font-face|fonts\.googleapis|fonts\.gstatic", css)),
                "kind": "exact",
                "why": "Zero. A webfont is a third-party origin, a render delay "
                       "and a hole in default-src 'none'. 2036 does not require "
                       "a new typeface."},
            "css.font_sizes": {
                "value": len(set(re.findall(r"font-size:\s*([^;]+);", css))),
                "kind": "ceiling",
                "why": "A ceiling, not a target. The sibling repository measures "
                       "418; that is what happens without a line."},
            "css.font_weights": {
                "value": len(set(re.findall(r"font-weight:\s*([^;]+);", css))),
                "kind": "ceiling", "why": "Four is enough for an editorial system."},
            "css.line_heights": {
                "value": len(set(re.findall(r"line-height:\s*([^;]+);", css))),
                "kind": "ceiling", "why": "Four."},
            "css.breakpoints": {
                "value": len(set(re.findall(
                    r"@media[^{]*\(m(?:in|ax)-width:\s*([^)]+)\)", css))),
                "kind": "ceiling",
                "why": "Six. Every one is a layout somebody has to test in "
                       "Chromium at two viewports."},
            "css.shadows": {
                "value": len(set(re.findall(r"box-shadow:\s*([^;]+);", css))),
                "kind": "ceiling", "why": "Two: a rest state and a lifted one."},
            "css.gold": {
                "value": len([h for h in re.findall(r"#[0-9a-fA-F]{6}", css)
                              if 90 <= int(h[1:3], 16) <= 215
                              and abs(int(h[1:3], 16) - int(h[3:5], 16)) < 55
                              and int(h[3:5], 16) - int(h[5:7], 16) > 45
                              and int(h[1:3], 16) - int(h[5:7], 16) > 70]),
                "kind": "exact",
                "why": "Zero. Gold says luxury, premium, wealth; this product "
                       "has to say Europe, discovery, movement, intelligence."},
            "js.applications": {
                "value": len(apps), "kind": "exact",
                "why": "Five. An application fetches an index or owns client "
                       "state and must declare its dependencies."},
            "js.enhancements": {
                "value": len(enh), "kind": "exact",
                "why": "Scripts that do neither and work on markup already in "
                       "the page."},
            "safety.inline_styles": {
                "value": sum(len(re.findall(r'\sstyle="', b)) for b in bodies.values()),
                "kind": "exact",
                "why": "Zero. One style attribute forces style-src open on "
                       "every page, and CSP hashes do not apply to them."},
            "safety.inline_style_blocks": {
                "value": sum(b.count("<style") for b in bodies.values()),
                "kind": "exact", "why": "Zero. A page may not ship its own CSS."},
            "safety.img_tags": {
                "value": sum(b.count("<img") for b in bodies.values()),
                "kind": "exact",
                "why": "Zero today, because zero photographs are licensed. This "
                       "moving is the signal that licensed imagery arrived — "
                       "which must go through the licence register first."},
            "plates.motifs_declared": {
                "value": len(R.MOTIFS), "kind": "exact",
                "why": "Seven declared."},
            "plates.motifs_reachable": {
                "value": _reachable(), "kind": "exact",
                "why": "Seven drawn. `plain` was declared and never reached for "
                       "the life of the plate system, because food -> plain sat "
                       "below eight interests almost every European destination "
                       "carries. A motif nothing reaches is dead code that looks "
                       "like vocabulary."},
            "primitives.reach": {
                "value": prim_floor, "kind": "floor",
                "why": "The share of pages each primitive appears on. A family "
                       "that stops using `row` has grown its own components and "
                       "the design system has forked without anybody deciding."},
        },
    }


def main(argv):
    got = measure()
    if "--write" in argv:
        with open(REG, "w", encoding="utf-8") as fh:
            json.dump(got, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        print(f"wrote {REG} — {len(got['invariants'])} invariants")
        return 0

    if not os.path.exists(REG):
        print("docs/invariants.json is missing — run --write")
        return 1
    with open(REG, encoding="utf-8") as fh:
        want = json.load(fh)["invariants"]
    bad = 0
    for name, spec in sorted(want.items()):
        now = got["invariants"].get(name, {}).get("value")
        exp, kind = spec["value"], spec["kind"]
        if kind == "floor" and isinstance(exp, dict):
            for k, v in exp.items():
                if now.get(k, 0) < v:
                    print(f"FAIL {name}.{k}: {now.get(k)} is below the recorded "
                          f"floor {v} — {spec['why']}")
                    bad += 1
        elif kind == "ceiling":
            if now > exp:
                print(f"FAIL {name}: {now} exceeds the recorded ceiling {exp} — "
                      f"{spec['why']}")
                bad += 1
        elif now != exp:
            print(f"FAIL {name}: {now!r}, recorded {exp!r} — {spec['why']}")
            bad += 1
    if bad:
        print(f"\n{bad} invariant(s) moved. If that was deliberate, run "
              f"tools/invariants.py --write in the same commit and say why.")
        return 1
    print(f"all {len(want)} invariants hold")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
