#!/usr/bin/env python3
"""Within-motif variation, measured by RENDERING.

    python3 tools/plate-variation.py            report
    python3 tools/plate-variation.py --write    record the twin counts
    python3 tools/plate-variation.py --check    fail if any family got MORE
                                                interchangeable

Not part of tools/checks.py: it renders 319 plates and compares every pair,
which is eight seconds. A gate that adds eight seconds to every build is a
gate people stop running.


Three earlier versions of this instrument were wrong, each in a way that
produced a confident number:

  1. bounding boxes — a ridge polygon spans the whole frame, so every peaks
     plate collapsed to one constant vector: "92% duplication" in a family
     that has none.
  2. no ellipses — isles is drawn from ellipses, so every isles plate was
     the flat water line: "79% duplication".
  3. silhouette only — isles' islands sit BELOW the horizon, so they are
     interior detail and never touch the top profile at all. The metric
     could not see the thing that varies.

Measuring a drawing requires drawing it. This renders every plate at 64x40
through the same rasteriser the social cards use and compares pixels, which
is what a reader's eye does with a card.
"""
import json, os, sys, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
os.chdir(ROOT)
from lib import data as D, render as R, raster                     # noqa: E402

BASELINE = os.path.join(ROOT, "docs", "plate-variation.json")

W, H = 64, 40


def pixels(seed, motif):
    sky_a, sky_b, prims = R.plate_shapes(seed, W, H, motif)
    c = raster.Canvas(W, H)
    c.vertical_gradient(sky_a, sky_b)
    for p in prims:
        if p[0] == "poly":
            c.polygon(p[1], p[2], p[3])
        elif p[0] == "rect":
            c.rect(p[1], p[2], p[3], p[4], p[5], p[6])
        elif p[0] == "circle":
            c.ellipse(p[1], p[2], p[3], p[3], p[4], p[5])
        elif p[0] == "ellipse":
            c.ellipse(p[1], p[2], p[3], p[4], p[5], p[6])
    return b"".join(bytes(r) for r in c.rows)


def dist(a, b):
    return sum(abs(x - y) for x, y in zip(a, b)) / (len(a) * 255.0)


d = D.load()
fam = collections.defaultdict(list)
for cid, n in sorted(d["cities"].items()):
    t, r, c = n["city"], n["region"], n["country"]
    m = R.motif_for(t["interests"], t.get("city_type")) or R.motif_for(r["interests"])
    fam[m].append((t["name"], pixels(f'city:{c["slug"]}:{t["slug"]}', m)))

print(f"{'motif':<9}{'n':>4}{'mean d':>9}{'near d':>9}{'twins':>7}{'twin%':>7}  closest pair")
print("-" * 88)
rows = []
for m in sorted(fam, key=lambda k: -len(fam[k])):
    items = fam[m]
    if len(items) < 2:
        continue
    ds, near, twins = [], [], 0
    worst = (9, "", "")
    for i, (na, pa) in enumerate(items):
        best = (9, "")
        for j, (nb, pb) in enumerate(items):
            if i == j:
                continue
            dd = dist(pa, pb)
            if j > i:
                ds.append(dd)
            if dd < best[0]:
                best = (dd, nb)
            if dd < 0.020 and j > i:
                twins += 1
        near.append(best[0])
        if best[0] < worst[0]:
            worst = (best[0], na, best[1])
    mean = sum(ds) / len(ds)
    nm = sum(near) / len(near)
    tp = 100 * twins / (len(items) * (len(items) - 1) / 2)
    print(f"{m:<9}{len(items):>4}{mean:>9.4f}{nm:>9.4f}{twins:>7}{tp:>6.1f}%  "
          f"{worst[1][:22]} / {worst[2][:22]} ({worst[0]:.4f})")
    rows.append((m, len(items), nm, twins, tp))

print()
print("mean d = average pixel difference between any two plates in the family")
print("near d = average difference to the NEAREST other plate — interchangeability")
print("twins  = pairs under 2% pixel difference")
print()
for m, n, nm, tw, tp in sorted(rows, key=lambda r: -r[4])[:3]:
    print(f"least varied: {m:<9} n={n:<4} near d={nm:.4f}  twins={tw} ({tp:.1f}% of pairs)")

# ── the gate ─────────────────────────────────────────────────────────────
#
# A ceiling on twin pairs per family. Variation is easy to lose by accident —
# a constant reintroduced, a seeded parameter narrowed — and the loss is
# invisible on any single plate. This is the number that made the difference
# between "the plates look a bit samey" and "coast has 125 interchangeable
# pairs out of 1,596".
got = {m: tw for m, _n, _nm, tw, _tp in rows}
if "--write" in sys.argv:
    with open(BASELINE, "w", encoding="utf-8") as fh:
        json.dump({"$comment": "GENERATED by tools/plate-variation.py --write. "
                               "A CEILING on interchangeable pairs per motif "
                               "family: pairs whose rendered 64x40 plates differ "
                               "by under 2% of pixel value. Going UP means the "
                               "atlas got more repetitive.",
                   "twin_pairs": got}, fh, indent=2)
        fh.write("\n")
    print(f"\nwrote {BASELINE}")
elif "--check" in sys.argv:
    if not os.path.exists(BASELINE):
        print("no baseline — run --write")
        sys.exit(1)
    with open(BASELINE, encoding="utf-8") as fh:
        want = json.load(fh)["twin_pairs"]
    bad = 0
    for m, ceiling in sorted(want.items()):
        now = got.get(m, 0)
        if now > ceiling:
            print(f"FAIL {m}: {now} interchangeable pairs, ceiling {ceiling} — "
                  f"the family got more repetitive")
            bad += 1
    print("" if bad else f"\nall {len(want)} motif families hold their variation")
    sys.exit(1 if bad else 0)
